services:
    user_user.registration.form.type:
        class: User\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_userbundle_registration }
    user_user.form.handler.registration:
        class: User\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user_registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false