<?php

namespace Main\FrontBundle\Repository;

/**
 * cmdorderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cmdorderRepository extends \Doctrine\ORM\EntityRepository
{
}
