<?php

namespace Main\FrontBundle\Repository;

/**
 * commandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandRepository extends \Doctrine\ORM\EntityRepository
{
}
