<?php

namespace Main\FrontBundle\Repository;

/**
 * paramtplRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paramtplRepository extends \Doctrine\ORM\EntityRepository
{
}
