<?php

namespace Main\FrontBundle\Repository;

/**
 * PlisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plisRepository extends \Doctrine\ORM\EntityRepository
{
}
