<?php

namespace Main\FrontBundle\Repository;

/**
 * prodoptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prodoptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
