<?php

namespace Main\FrontBundle\Repository;

/**
 * prodimgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prodimgRepository extends \Doctrine\ORM\EntityRepository
{
}
