<?php

namespace Main\FrontBundle\Repository;

/**
 * socialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class socialRepository extends \Doctrine\ORM\EntityRepository
{
}
