<?php

namespace Main\FrontBundle\Repository;

/**
 * tplprodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tplprodRepository extends \Doctrine\ORM\EntityRepository
{
}
