main_front_homepage:
    path:     /
    defaults: { _controller: MainFrontBundle:Default:index }
pages_contenue:
    path:     /yasmine-press/{slug}
    defaults: { _controller: MainFrontBundle:Page:index }
demande_devis:
    path:     /yasmine-press/imprimerie/demandedevis
    defaults: { _controller: MainFrontBundle:Page:devis }
form_contact:
    path:     /yasmine-press/imprimerie/contact
    defaults: { _controller: MainFrontBundle:Page:contact }
boutique:
    path:     /yasminepress/boutique
    defaults: { _controller: MainFrontBundle:Products:index }
boutique_detail:
    path:     /yasminepress/boutique/{id}/{slug}/
    defaults: { _controller: MainFrontBundle:Products:detail }
submit_details:
    path:     /submitdetails
    defaults: { _controller: MainFrontBundle:Caddy:submitdetails }
panier:
    path:     /panier
    defaults: { _controller: MainFrontBundle:Caddy:panier }
panier_delete:
    path:     /panier/{id}
    defaults: { _controller: MainFrontBundle:Caddy:panierdelete }
gettemplates:
    path:     /api/{id}/templates
    defaults: { _controller: MainFrontBundle:Ajax:listTemplate }
puttemplates:
    path:     /api/puttemplates
    defaults: { _controller: MainFrontBundle:Ajax:puttemplate }
generatepdf:
    path:     /generatepdf
    defaults: { _controller: MainFrontBundle:Ajax:generatepdf }