main_front_homepage:
    path:     /
    defaults: { _controller: MainFrontBundle:Default:index }
pages_contenue:
    path:     /yasmine-press/{slug}
    defaults: { _controller: MainFrontBundle:Page:index }
demande_devis:
    path:     /yasmine-press/imprimerie/demandedevis
    defaults: { _controller: MainFrontBundle:Page:devis }
form_contact:
    path:     /yasmine-press/imprimerie/contact
    defaults: { _controller: MainFrontBundle:Page:contact }
boutique:
    path:     /yasminepress/boutique
    defaults: { _controller: MainFrontBundle:Products:index }
boutique_detail:
    path:     /yasminepress/boutique/{id}/{slug}/
    defaults: { _controller: MainFrontBundle:Products:detail }
submit_details:
    path:     /submitdetails
    defaults: { _controller: MainFrontBundle:Caddy:submitdetails }
panier:
    path:     /panier
    defaults: { _controller: MainFrontBundle:Caddy:panier }
validate_cmd:
    path:     /valider-ma-commande.html
    defaults: { _controller: MainFrontBundle:Caddy:ValidateCmd }
login_Page:
    path:     /connexion.html
    defaults: { _controller: MainFrontBundle:Caddy:Connexion }
login:
    path:     /login
    defaults: { _controller: MainFrontBundle:Caddy:login }
panier_delete:
    path:     /panier/{id}
    defaults: { _controller: MainFrontBundle:Caddy:panierdelete }
drawAccrodion:
    path:     /drawAccrodion/{id}
    defaults: { _controller: MainFrontBundle:Ajax:drawAccrodion }
gettemplates:
    path:     /api/{id}/templates
    defaults: { _controller: MainFrontBundle:Ajax:listTemplate }
puttemplates:
    path:     /api/puttemplates
    defaults: { _controller: MainFrontBundle:Ajax:puttemplate }
generatepdf:
    path:     /generatepdf/{id}
    defaults: { _controller: MainFrontBundle:Ajax:generatepdf }

uploadfiles:
    path:     /uploadfiles
    defaults: { _controller: MainFrontBundle:Ajax:uploadfiles }