services:

    admin.template:
        class: Main\FrontBundle\Admin\BannerAdmin
        arguments: [~, Main\FrontBundle\Entity\banner, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Bannière, group: Contenu}
    admin.pages:
        class: Main\FrontBundle\Admin\PagesAdmin
        arguments: [~, Main\FrontBundle\Entity\pages, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pages de contenu, group: Contenu}

    admin.categories:
        class: Main\FrontBundle\Admin\CategoriesAdmin
        arguments: [~, Main\FrontBundle\Entity\category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Produits, group: Produithèque}


    admin.formula:
        class: Main\FrontBundle\Admin\FormulaAdmin
        arguments: [~, Main\FrontBundle\Entity\formule, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Demande de devis, group: Feedback, icon: '<i class="fa fa-archive"></i>'}

    admin.contact:
        class: Main\FrontBundle\Admin\ContactAdmin
        arguments: [~, Main\FrontBundle\Entity\contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Contact, group: Feedback,  icon: '<i class="fa fa-archive"></i>'}















# services utils
    Tools.utils:
        class: Main\FrontBundle\Services\ToolsServices