services:

    admin.template:
        class: Main\FrontBundle\Admin\BannerAdmin
        arguments: [~, Main\FrontBundle\Entity\banner, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Bannière, group: Contenu}
    admin.pages:
        class: Main\FrontBundle\Admin\PagesAdmin
        arguments: [~, Main\FrontBundle\Entity\pages, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pages de contenu, group: Contenu}

    admin.social:
        class: Main\FrontBundle\Admin\SocialAdmin
        arguments: [~, Main\FrontBundle\Entity\social, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Réseaux sociaux, group: Contenu}

    admin.categories:
        class: Main\FrontBundle\Admin\CategoriesAdmin
        arguments: [~, Main\FrontBundle\Entity\category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Produits, group: Produithèque}
        calls:
            - [addChild, ['@admin.tplprod']]
            - [addChild, ['@admin.prodimg']]
            - [ setTemplate, [edit, MainFrontBundle:category:edit.html.twig]]
    admin.plis:
        class: Main\FrontBundle\Admin\PlisAdmin
        arguments: [~, Main\FrontBundle\Entity\plis, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Type des plis, group: Produithèque}
    admin.prodoptions:
        class: Main\FrontBundle\Admin\ProdoptionsAdmin
        arguments: [~, Main\FrontBundle\Entity\prodoptions, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
    admin.paramtpl:
        class: Main\FrontBundle\Admin\ParamtplAdmin
        arguments: [~, Main\FrontBundle\Entity\paramtpl, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
    admin.tplprod:
        class: Main\FrontBundle\Admin\TplprodAdmin
        arguments: [~, Main\FrontBundle\Entity\tplprod, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        calls:
            - [ setTemplate, [edit, MainFrontBundle:tplprod:edit.html.twig]]
    admin.prodimg:
        class: Main\FrontBundle\Admin\ProdimgAdmin
        arguments: [~, Main\FrontBundle\Entity\prodimg, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        calls:
            - [ setTemplate, [edit, MainFrontBundle:Prodimg:edit.html.twig]]

    admin.formula:
        class: Main\FrontBundle\Admin\FormulaAdmin
        arguments: [~, Main\FrontBundle\Entity\formule, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Demande de devis, group: Feedback, icon: '<i class="fa fa-archive"></i>'}

    admin.contact:
        class: Main\FrontBundle\Admin\ContactAdmin
        arguments: [~, Main\FrontBundle\Entity\contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Contact, group: Feedback,  icon: '<i class="fa fa-archive"></i>'}



    admin.reservation:
        class: Main\FrontBundle\Admin\ReservationAdmin
        arguments: [~, Main\FrontBundle\Entity\command, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Réservation, group: Feedback,  icon: '<i class="fa fa-archive"></i>'}















# services utils
    Tools.utils:
        class: Main\FrontBundle\Services\ToolsServices