services:

    admin.template:
        class: Main\FrontBundle\Admin\BannerAdmin
        arguments: [~, Main\FrontBundle\Entity\banner, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Bannière, group: Contenu}
    admin.pages:
        class: Main\FrontBundle\Admin\PagesAdmin
        arguments: [~, Main\FrontBundle\Entity\pages, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pages de contenu, group: Contenu}

    admin.categories:
        class: Main\FrontBundle\Admin\CategoriesAdmin
        arguments: [~, Main\FrontBundle\Entity\category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Catégorie des produits, group: Produithèque}

    admin.produits:
        class: Main\FrontBundle\Admin\ProductsAdmin
        arguments: [~, Main\FrontBundle\Entity\products, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Produits, group: Produithèque}















# services utils
    Tools.utils:
        class: Main\FrontBundle\Services\ToolsServices