#annexe
user_contract_homepage:
    path:     /{user_id}
    defaults: { _controller: UserUserBundle:Contract:index }
    requirements:
        user_id: \d+

user_contract_show:
    path:     /{user_id}/view/{id}
    defaults: { _controller: UserUserBundle:Contract:show}
    requirements:
        id: \d+

user_contract_add_manager:
    path:     /{user_id}/add
    defaults: { _controller: UserUserBundle:Contract:add }
user_contract_update_manager:
    path:     /{user_id}/update/{id}
    defaults: { _controller: UserUserBundle:Contract:edit}
    requirements:
        id: \d+
