<?php
/**
 * Created by PhpStorm.
 * User: sarra
 * Date: 09/08/16
 * Time: 09:37
 */

namespace Main\FrontBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;

class ParamtplAdmin extends Admin
{
    public function getname()
    {
        return 'Parameter de template';
    }

    public function getNewInstance()
    {
        return parent::getNewInstance(); // TODO: Change the autogenerated stub
    }

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('name');
        $formMapper->add('type', 'choice', array(
            'placeholder' => 'choisisser un type',
            'choices' => array(
                '0' => 'Text',
                '1' => 'Image'
            ),));
        $formMapper->add('x1');
        $formMapper->add('y1');
        $formMapper->add('x2');
        $formMapper->add('y2');
        $formMapper->add('size');
        $formMapper->add('police');
        $formMapper->add('align', 'choice', array(
            'placeholder' => 'choisisser un type',
            'choices' => array(
                'C' => 'center',
                'L' => 'left',
                'R' => 'right'
            ),));
        $formMapper->add('color');

    }

}