<?php
/**
 * Created by PhpStorm.
 * User: sarra
 * Date: 09/08/16
 * Time: 09:37
 */

namespace Main\FrontBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;

class TplprodAdmin extends Admin
{
    protected $parentAssociationMapping = 'category';

    public function getname()
    {
        return 'Template des produits';
    }

    public function getNewInstance()
    {
        return parent::getNewInstance(); // TODO: Change the autogenerated stub
    }

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('bg', 'text', array("label" => "Fichier", 'required' => false));
        $formMapper->add('name', 'text', array("label" => "Nom de Fichier"));
        $formMapper->add('pdf', 'text', array("label" => "Fichier Pdf"));
        $formMapper->add('parameters', 'sonata_type_collection', array(
            'by_reference' => false
        ), array(
            'edit' => 'inline',
            'inline' => 'table',
            'sortable' => 'position',
        ));
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add("bg", null, array('template' => 'MainFrontBundle:Fields:imgtplprod.html.twig'))
            ->add("name")
            ->add("pdf")
            ->add('_action', 'actions', array(
                'actions' => array(
                    'edit' => array(),
                    'delete' => array(),

                )));
    }
    private function updateParent($object){
        foreach($object->getParameters() as $param){
            $param->setTpl($object);
        }
    }
    public function prePersist($object)
    {
        $this->updateParent($object);
    }
    public function preUpdate($object)
    {
        $this->updateParent($object);
    }
}