main_back:
    resource: "@MainBackBundle/Resources/config/routing.yml"
    prefix:   /Manager

user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /Manager

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
