#categorie
back_banner:
    path:     /
    defaults: { _controller: MainBackBundle:Banner:index }

add_banner_manager:
    path:     /add
    defaults: { _controller: MainBackBundle:Banner:add }
update_banner_manager:
    path:     /update/{id}
    defaults: { _controller: MainBackBundle:Banner:edit}
    requirements:
        id: \d+
delete_banner_manager:
    path:     /delete/{id}
    defaults: { _controller: MainBackBundle:Banner:delete}
    requirements:
        id: \d+
show_banner_manager:
    path:     /show/{id}
    defaults: { _controller: MainBackBundle:Banner:show}
    requirements:
        id: \d+