<?php

namespace MailingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cfgmailingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cfgmailingRepository extends EntityRepository
{
}
