<?php

namespace MailingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * mailinglistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mailinglistRepository extends EntityRepository
{
}
