<?php

namespace MailingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * processmailingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class processmailingRepository extends EntityRepository
{
}
