main_back_homepage:
    path:     /home
    defaults: { _controller: MainBackBundle:Default:index }


back_category:
    resource: "@MainBackBundle/Resources/config/routing/category.yml"
    prefix:   /category

back_banner:
    resource: "@MainBackBundle/Resources/config/routing/banner.yml"
    prefix:   /banner

back_pages:
    resource: "@MainBackBundle/Resources/config/routing/pages.yml"
    prefix:   /pages