main_back_homepage:
    path:     /home
    defaults: { _controller: MainBackBundle:Default:index }


back_category:
    resource: "@MainBackBundle/Resources/config/routing/category.yml"
    prefix:   /category