<?php

namespace PrintBundle\Repository;

/**
 * pdflistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pdflistRepository extends \Doctrine\ORM\EntityRepository
{
}
