<?php

namespace PrintBundle\Repository;

/**
 * PdfmergeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfmergeRepository extends \Doctrine\ORM\EntityRepository
{
}
