<?php

namespace Main\BackBundle\Repository;

/**
 * bannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bannerRepository extends \Doctrine\ORM\EntityRepository
{
}
